import assert from 'node:assert/strict';
import { mkdtemp, rm, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const dir = await mkdtemp(join(tmpdir(), 'syukatu-ui-'));
process.env.DATA_FILE = join(dir, 'data.json');
const shots = resolve(process.env.UI_SCREENSHOT_DIR || join('artifacts', 'latest-ui-checks'));
let server, browser;
try {
  const modulePath = process.env.PLAYWRIGHT_MODULE || 'C:/Users/81805/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
  const { chromium } = await import(pathToFileURL(modulePath).href);
  const [{ JsonStore }, { createAppServer }] = await Promise.all([import('../src/store.mjs'), import('../server.mjs')]);
  const store = await new JsonStore(process.env.DATA_FILE).init();
  const organizer = async ({ originalText }) => {
    if (originalText === '失敗確認') throw Object.assign(new Error('一時的な失敗'), { status: 503 });
    if (originalText === 'キャンセル確認') return new Promise(r => setTimeout(() => r({ cards: [{ title: '遅延結果', body: '保存しない', categoryIds: [] }] }), 600));
    if (originalText === '保存失敗確認') return { cards: [{ title: '要修正', body: 'あ'.repeat(701), categoryIds: [] }] };
    await new Promise(r => setTimeout(r, 150));
    return { cards: [{ title: '面接日程', body: '9月26日14時。オンライン。', categoryIds: [] }, { title: '初任給', body: '28万円。', categoryIds: [] }] };
  };
  server = createAppServer({ appStore: store, organizer });
  await new Promise(r => server.listen(0, '127.0.0.1', r));
  const origin = 'http://127.0.0.1:' + server.address().port;
  browser = await chromium.launch({ headless: true, executablePath: process.env.BROWSER_EXECUTABLE || 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
  await mkdir(shots, { recursive: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 }, locale: 'ja-JP', timezoneId: 'Asia/Tokyo', reducedMotion: 'reduce' });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error' && !m.text().startsWith('Failed to load resource')) errors.push(m.text()); });
  await page.goto(origin);
  await page.locator('h1').filter({ hasText: 'ホーム' }).waitFor();
  assert.equal(await page.getByText('最近追加').count(), 0);
  await page.screenshot({ path: join(shots, 'desktop-home.png') });
  await page.locator('.main-nav [data-nav="companies"]').click();
  await page.locator('#add-company').click();
  await page.locator('#f-name').fill('   ');
  await page.locator('form button[type="submit"]').click();
  await page.locator('[role="alert"]').filter({ hasText: '企業名を入力' }).waitFor();
  await page.locator('#f-name').fill('とても長い名前の企業'.repeat(8));
  await page.locator('form button[type="submit"]').click();
  await page.locator('.company-card').first().waitFor();
  await page.screenshot({ path: join(shots, 'desktop-companies.png') });
  const companyId = store.snapshot().companies[0].id;
  await page.locator(`[data-company="${companyId}"]`).click();
  await page.locator('#add-card').click();
  await page.locator('#f-title').fill('   ');
  await page.locator('#f-body').fill('   ');
  await page.locator('form button[type="submit"]').click();
  assert.equal(await page.locator('.has-error').count(), 2);
  await page.locator('#f-title').fill('面接予定');
  await page.locator('#f-body').fill('手動入力した本文'.repeat(40));
  await page.locator('#f-eventDate').fill('2026-09-26');
  await page.locator('[name="pinned"]').check();
  await page.locator('#manage-categories').click();
  await page.locator('#f-name').fill('面接');
  await page.locator('#category-form button[type="submit"]').click();
  await page.locator('#back-categories').click();
  assert.equal(await page.locator('#f-title').inputValue(), '面接予定');
  await page.locator('[data-category]').first().click();
  await page.locator('form button[type="submit"]').click();
  await page.locator('.card-list .info-card').first().waitFor();
  assert.equal(await page.locator('.screen.detail-screen').count(), 0, '作成後は詳細に留まらない');
  assert.equal(await page.locator('.inline-notice').textContent(), '情報カードを保存しました');
  await page.screenshot({ path: join(shots, 'desktop-save-success.png') });
  const manual = store.snapshot().cards.find(c => c.title === '面接予定');
  assert.ok(manual?.pinned);
  assert.equal(manual?.eventDate, '2026-09-26');
  assert.equal(manual?.categoryIds.length, 1);
  await page.locator(`[data-card="${manual.id}"]`).click();
  await page.locator('#pin').click();
  await page.waitForFunction(() => document.querySelector('#pin')?.textContent === 'ピン留め');
  assert.equal(store.snapshot().cards.find(c => c.id === manual.id).pinned, false);
  await page.locator('#pin').click();
  await page.waitForFunction(() => document.querySelector('#pin')?.textContent === 'ピン留め解除');
  assert.equal(store.snapshot().cards.find(c => c.id === manual.id).pinned, true);
  await page.locator('#edit').click();
  await page.locator('#f-title').fill('面接予定 更新');
  await page.screenshot({ path: join(shots, 'desktop-card-form.png') });
  await page.goBack();
  await page.locator('#dialog-back').click();
  assert.equal(await page.locator('#f-title').inputValue(), '面接予定 更新', 'ブラウザBackの破棄を取り消して入力を維持');
  await page.locator('#cancel-form').click();
  await page.locator('#dialog-back').click();
  assert.equal(await page.locator('#f-title').inputValue(), '面接予定 更新');
  await page.locator('form button[type="submit"]').click();
  await page.locator('.card-list .info-card').first().waitFor();
  assert.equal(await page.locator('.inline-notice').textContent(), '情報カードを保存しました', '編集後も一覧に成功通知');
  await page.locator('.main-nav [data-nav="home"]').click();
  await page.locator('#sort').selectOption('oldest');
  await page.locator('#sort').selectOption('nearest');
  await page.locator('#sort').selectOption('newest');
  await page.screenshot({ path: join(shots, 'desktop-home-pinned.png') });
  await page.locator('.main-nav [data-nav="ai"]').click();
  await page.locator('#f-originalText').fill('失敗確認');
  await page.locator('form button[type="submit"]').click();
  await page.locator('[role="alert"]').filter({ hasText: '一時的な失敗' }).waitFor();
  assert.equal(await page.locator('#f-originalText').inputValue(), '失敗確認');
  await page.locator('#f-originalText').fill('キャンセル確認');
  await page.locator('form button[type="submit"]').click();
  await page.locator('#stop-ai').click();
  await page.waitForTimeout(700);
  assert.equal(await page.locator('#f-originalText').inputValue(), 'キャンセル確認');
  await page.locator('#f-originalText').fill('保存失敗確認');
  await page.locator('form button[type="submit"]').click();
  await page.locator('.draft-card').first().waitFor();
  await page.locator('#save-drafts').click();
  await page.locator('.review-wrap .error-text').filter({ hasText: '700文字' }).waitFor();
  assert.match(await page.locator('.source-panel').textContent(), /保存失敗確認/);
  await page.locator('[data-edit="0"]').click();
  await page.locator('#f-body').fill('修正後の本文');
  await page.locator('form button[type="submit"]').click();
  await page.locator('#save-drafts').click();
  await page.locator('.card-list .info-card').first().waitFor();
  assert.equal(await page.locator('.inline-notice').textContent(), '情報カードを保存しました', 'AI保存後も一覧に成功通知');
  await page.locator('.main-nav [data-nav="ai"]').click();
  await page.locator('#f-originalText').fill('面接日程と初任給');
  await page.locator('form button[type="submit"]').click();
  await page.locator('.draft-card').first().waitFor();
  assert.equal(await page.locator('.draft-card').count(), 2);
  await page.screenshot({ path: join(shots, 'desktop-ai-review.png') });
  await page.locator('[data-edit="1"]').click();
  await page.locator('#f-title').fill('初任給の確認');
  await page.locator('form button[type="submit"]').click();
  assert.equal(await page.locator('.draft-card').count(), 2);
  await page.locator('#save-drafts').click();
  await page.locator('.card-list .info-card').first().waitFor();
  assert.equal(store.snapshot().cards.filter(c => c.isAiGenerated).length, 3);
  const savedAi = store.snapshot().cards.find(c => c.title === '面接日程');
  await page.locator(`[data-card="${savedAi.id}"]`).click();
  assert.match(await page.locator('.detail-panels .paper-panel').first().textContent(), /面接日程と初任給/);
  await page.locator('.main-nav [data-nav="self"]').click();
  await page.locator('#add-card').click();
  await page.locator('#manage-categories').click();
  await page.screenshot({ path: join(shots, 'desktop-categories.png') });
  await page.locator('[data-delete-category]').first().click();
  await page.locator('#dialog-do').click();
  await page.locator('.category-list .empty').waitFor();
  assert.ok(store.snapshot().cards.every(c => !c.categoryIds.includes(manual.categoryIds[0])));
  assert.ok(store.snapshot().cards.some(c => c.id === manual.id), 'カテゴリー削除後もカードは残る');
  await page.locator('#back-categories').click();
  await page.locator('#cancel-form').click();
  await page.locator('.main-nav [data-nav="companies"]').click();
  await page.locator(`[data-company="${companyId}"]`).click();
  await page.locator('[data-card]').first().click();
  await page.locator('#delete').click();
  await page.locator('#dialog-do').click();
  await page.locator('.card-list').waitFor();
  assert.equal(await page.locator('.inline-notice').textContent(), 'カードを削除しました', '削除後も一覧に成功通知');
  assert.equal(store.snapshot().cards.some(c => c.id === manual.id), false);
  await store.update(state => { for (let i = 0; i < 12; i++) state.cards.push({ id: 'stress-' + i, title: '長いピン留めタイトル'.repeat(4) + i, body: '長文の内容。'.repeat(120), destination: { type: 'self', companyId: null }, categoryIds: [], eventDate: null, createdAt: new Date(Date.now() - i * 1000).toISOString(), updatedAt: new Date().toISOString(), pinned: true, pinnedAt: new Date().toISOString(), originalText: null, isAiGenerated: false }); });
  await page.goto(origin);
  await page.locator('.pin-list.is-compact').waitFor();
  await page.screenshot({ path: join(shots, 'desktop-pins-collapsed.png') });
  await page.locator('[data-expand]').first().click();
  assert.equal(await page.locator('[data-expand]').first().getAttribute('aria-expanded'), 'true');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(origin);
  await page.locator('.mobile-nav [data-nav="home"]').click();
  await page.locator('.pin-list.is-compact').waitFor();
  await page.screenshot({ path: join(shots, 'mobile-pins-collapsed.png') });
  await page.locator('[data-expand]').first().click();
  assert.equal(await page.locator('[data-expand]').first().getAttribute('aria-expanded'), 'true');
  await page.screenshot({ path: join(shots, 'mobile-pins-expanded.png') });
  await page.locator('.mobile-nav [data-nav="ai"]').click();
  await page.screenshot({ path: join(shots, 'mobile-ai-source.png') });
  await page.locator('.mobile-nav [data-nav="self"]').click();
  await page.locator('#mobile-add-card').click();
  await page.screenshot({ path: join(shots, 'mobile-card-form.png') });
  const destinationTop = await page.locator('.form-side .form-box').first().evaluate(el => el.getBoundingClientRect().top);
  const titleTop = await page.locator('#f-title').evaluate(el => el.getBoundingClientRect().top);
  assert.ok(destinationTop < titleTop, 'モバイルでは保存先をタイトルより先に表示');
  await store.update(state => { for (let i = 0; i < 15; i++) state.categories.push({ id: 'stress-category-' + i, name: '長いカテゴリー名'.repeat(3) + i, createdAt: new Date().toISOString() }); });
  await page.goto(origin);
  await page.locator('.mobile-nav [data-nav="self"]').click();
  await page.locator('#mobile-add-card').click();
  await page.screenshot({ path: join(shots, 'mobile-many-categories.png') });
  await page.locator('[data-category="stress-category-14"]').scrollIntoViewIfNeeded();
  assert.equal(await page.locator('[data-category="stress-category-14"]').isVisible(), true);
  const lastChipBounds = await page.locator('[data-category="stress-category-14"]').evaluate(el => ({ bottom: el.getBoundingClientRect().bottom, actionTop: document.querySelector('.form-actions').getBoundingClientRect().top }));
  assert.ok(lastChipBounds.bottom < lastChipBounds.actionTop, '固定アクションが最後のカテゴリーを覆わない');
  await page.locator('#f-title').fill('モバイルから作成したカード');
  await page.locator('#f-body').fill('モバイルで保存した本文');
  await page.locator('form button[type="submit"]').click();
  await page.locator('.card-list .info-card').filter({ hasText: 'モバイルから作成したカード' }).waitFor();
  assert.equal(await page.locator('.inline-notice').textContent(), '情報カードを保存しました');
  await page.screenshot({ path: join(shots, 'mobile-save-success.png') });
  await page.waitForTimeout(4200);
  assert.equal(await page.locator('.inline-notice').count(), 0, '成功通知は約4秒後に消える');
  await page.locator('.card-list .info-card').filter({ hasText: 'モバイルから作成したカード' }).click();
  assert.equal(await page.locator('.inline-notice').count(), 0, '詳細画面へ通知を持ち越さない');
  await page.locator('#edit').click();
  await page.locator('#f-body').fill('モバイルで編集した本文');
  await page.locator('form button[type="submit"]').click();
  await page.locator('.card-list .info-card').filter({ hasText: 'モバイルから作成したカード' }).waitFor();
  assert.equal(await page.locator('.inline-notice').textContent(), '情報カードを保存しました', 'モバイル編集後は一覧で通知');
  await page.screenshot({ path: join(shots, 'mobile-edit-save-success.png') });
  await page.locator('.card-list .info-card').filter({ hasText: 'モバイルから作成したカード' }).click();
  assert.match(await page.locator('.single-panel').textContent(), /モバイルで編集した本文/);
  assert.equal(await page.locator('.inline-notice').count(), 0);
  await page.locator('#mobile-pin').click();
  await page.waitForFunction(() => document.querySelector('#mobile-pin')?.textContent === 'ピン留め解除');
  await page.screenshot({ path: join(shots, 'mobile-card-detail.png') });
  await page.locator('.mobile-nav [data-nav="self"]').click();
  await page.locator(`[data-card="${savedAi.id}"]`).click();
  assert.equal(await page.locator('.detail-tabs').isVisible(), true);
  await page.locator('[data-detail-tab="original"]').click();
  assert.equal(await page.locator('.detail-panels .paper-panel').first().isVisible(), true);
  await page.screenshot({ path: join(shots, 'mobile-ai-original.png') });
  await store.update(state => {
    state.companies.push({ id: 'qa-company', name: 'CyberAgent', createdAt: '2026-09-01T00:00:00.000Z' });
    state.categories.push({ id: 'qa-interview', name: '面接', createdAt: '2026-09-01T00:00:00.000Z' });
    state.cards.push({ id: 'qa-m06', title: '一次面接について', body: '面接日：9月26日\n開始：14時\n形式：オンライン\n服装：自由\n所要時間：15〜20分\n接続URL：前日に案内予定', destination: { type: 'company', companyId: 'qa-company' }, categoryIds: ['qa-interview'], eventDate: '2026-09-26', createdAt: '2026-09-22T00:00:00.000Z', updatedAt: '2026-09-23T00:00:00.000Z', pinned: false, pinnedAt: null, isAiGenerated: true, originalText: '面接は9月26日の14時から。オンライン。服装は自由で、15〜20分くらい。URLは前日に届く予定。' });
  });
  await page.goto(origin);
  await page.locator('.mobile-nav [data-nav="companies"]').click();
  await page.locator('[data-company="qa-company"]').click();
  await page.locator('[data-card="qa-m06"]').click();
  assert.equal(await page.locator('#edit').isVisible(), true, 'M06の編集ボタンを表示');
  const detailBounds = await page.evaluate(() => Object.fromEntries([['tabs','.detail-tabs'],['meta','.detail-meta'],['body','.ai-panel'],['actions','.detail-actions'],['delete','#delete'],['pin','#mobile-pin']].map(([key,selector]) => { const r=document.querySelector(selector).getBoundingClientRect();return [key,{x:r.x,y:r.y,width:r.width,height:r.height}]; })));
  assert.ok(detailBounds.tabs.y < detailBounds.meta.y && detailBounds.meta.y < detailBounds.body.y && detailBounds.body.y < detailBounds.actions.y, 'M06の情報順');
  assert.ok(detailBounds.delete.x < detailBounds.pin.x, '削除は左、ピン操作は右');
  assert.equal(Math.round(detailBounds.body.x), 20);
  assert.equal(Math.round(detailBounds.body.width), 350);
  await page.screenshot({ path: join(shots, 'mobile-m06-compare.png') });
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.screenshot({ path: join(shots, 'desktop-d06-compare.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('.mobile-nav [data-nav="other"]').click();
  await page.locator('#mobile-add-card').click();
  await page.locator('#f-title').fill('その他の確認');
  await page.locator('#f-body').fill('その他に保存する内容');
  await page.locator('form button[type="submit"]').click();
  assert.equal(await page.locator('.inline-notice').textContent(), '情報カードを保存しました', 'その他配下の作成後も一覧通知');
  await page.locator('.card-list .info-card').filter({ hasText: 'その他の確認' }).click();
  await page.locator('#edit').click();
  await page.locator('#f-body').fill('その他で編集した内容');
  await page.locator('form button[type="submit"]').click();
  assert.equal(await page.locator('.inline-notice').textContent(), '情報カードを保存しました', 'その他配下の編集後も一覧通知');
  await page.locator('.card-list .info-card').filter({ hasText: 'その他の確認' }).click();
  await page.locator('#delete').click();
  await page.locator('#dialog-do').click();
  assert.equal(await page.locator('.inline-notice').textContent(), 'カードを削除しました', 'その他配下の削除後も一覧通知');
  for (const width of [320, 390, 760, 1024, 1440]) {
    await page.setViewportSize({ width, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `${width}pxで横方向にはみ出さない`);
  }
  assert.deepEqual(errors, []);
  console.log('UI smoke passed. Screenshots:', shots);
} finally {
  if (browser) await browser.close();
  if (server) await new Promise(r => server.close(r));
  await rm(dir, { recursive: true, force: true });
}
